name: Deploy to Workshop

on:
  workflow_dispatch:
    inputs:
      changelog:
        type: string
        required: false
        default: "Update to latest Git commit"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: project
          ref: lua

      - name: Remove Non-content
        run: |
          rm -rf $GITHUB_WORKSPACE/project/.git*
          rm -fv $GITHUB_WORKSPACE/project/LICENSE*
          rm -fv $GITHUB_WORKSPACE/project/README*
      - uses: CFC-Servers/gmod-upload@master
        with:
          id: 3114942472
          changelog: ${{ inputs.changelog }}
          title: GM Sudo
          type: ServerContent
          tag1: fun
        env:
          STEAM_USERNAME: ${{ secrets.WORKSHOP_UPLOADER_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.WORKSHOP_UPLOADER_PASSWORD }}
